net: wireless: rockchip_wlan: bcmdhd: Fix compile error on kernel 6.1.160
drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/wl_cfg80211.c:25412:17: error: too few arguments to function 'cfg80211_port_authorized'; expected 5, have 3

Fixes: b9e2e550b9a2 ("cfg80211: Update Transition Disable policy during port authorization")
Change-Id: I2336553b07a43be2d273a1d900cd2af71279856c
Signed-off-by: Tao Huang <huangtao@rock-chips.com>