dt-bindings: usb: rockchip,pmic-tcpc: Fix yaml check errors
Fix the errors reported by dt_binding_check listed below:

Documentation/devicetree/bindings/usb/rockchip,pmic-tcpc.yaml:5:10: [error] string value is redundantly quoted with any quotes (quoted-strings)
  DTEX    Documentation/devicetree/bindings/usb/rockchip,pmic-tcpc.example.dts
  DTC [C] Documentation/devicetree/bindings/usb/rockchip,pmic-tcpc.example.dtb
Error: Documentation/devicetree/bindings/usb/rockchip,pmic-tcpc.example.dts:37.17-18 syntax error
Error: Documentation/devicetree/bindings/usb/rockchip,pmic-tcpc.example.dts:59.88-89 syntax error

Fixes: 8d0cdb98d767 ("dt-bindings: usb: Add rockchip pmic tcpc")
Signed-off-by: Frank Wang <frank.wang@rock-chips.com>
Change-Id: I90982c549d9688cd63116a44ad7440de08c3ab71