regulator: core: Fix building without CONFIG_DEBUG_FS
drivers/regulator/core.c:45:21: error: 'regulator_debug_mutex' defined but not used [-Werror=unused-variable]

Fixes: 5079f166e74a ("regulator: core: Fix regulator_debug_list data corruption")
Change-Id: I2565112eb3f22635e6e284cbfca3a1df71a91ab0
Signed-off-by: Tao Huang <huangtao@rock-chips.com>