Revert "drm: Kconfig: CONFIG_DRM select CONFIG_HDMI if !ROCKCHIP_MINI_KERNEL"
This reverts commit 7c7517b5c113ae9b9950b280678da5a4c2890136.

We need to find a better approach to disable HDMI functionality, such as
synchronously turning off both DRM_DISPLAY_HDMI_HELPER and DRM_DISPLAY_HDMI_STATE_HELPER.
Otherwise, merely disabling HDMI alone would cause compilation and linking issues.

drivers/gpu/drm/drm_debugfs.c:540:(.text+0x7bc): undefined reference to `hdmi_infoframe_pack'
drivers/gpu/drm/display/drm_hdmi_helper.c:50:(.text+0x164): undefined reference to `hdmi_drm_infoframe_init'
drivers/gpu/drm/display/drm_hdmi_state_helper.c:583:(.text+0x1a0): undefined reference to `hdmi_infoframe_pack'
drivers/gpu/drm/display/drm_hdmi_state_helper.c:383:(.text+0x7f4): undefined reference to `hdmi_spd_infoframe_init'

Change-Id: If3bc92604e1aeae137c137f9c382e8c9e2b844d5
Signed-off-by: Tao Huang <huangtao@rock-chips.com>