include: rockchip: rockchip_rockit.h: Fix missing-prototypes warnings when !ISP
drivers/media/platform/rockchip/cif/cif-rockit.c:93:5: error: no previous prototype for 'rkcif_rockit_buf_queue' [-Werror=missing-prototypes]
drivers/media/platform/rockchip/cif/cif-rockit.c:288:5: error: no previous prototype for 'rkcif_rockit_pause_stream' [-Werror=missing-prototypes]
drivers/media/platform/rockchip/cif/cif-rockit.c:305:5: error: no previous prototype for 'rkcif_rockit_config_stream' [-Werror=missing-prototypes]
drivers/media/platform/rockchip/cif/cif-rockit.c:331:5: error: no previous prototype for 'rkcif_rockit_resume_stream' [-Werror=missing-prototypes]
drivers/media/platform/rockchip/cif/cif-rockit.c:378:7: error: no previous prototype for 'rkcif_rockit_function_register' [-Werror=missing-prototypes]
drivers/media/platform/rockchip/cif/cif-rockit.c:401:5: error: no previous prototype for 'rkcif_rockit_get_cifdev' [-Werror=missing-prototypes]

Fixes: 89611a83d2a6 ("include: rockchip: rockchip_rockit.h support vicap")
Change-Id: Idab7d7cd1adff8efd78307bed63edaee331c4d6e
Signed-off-by: Tao Huang <huangtao@rock-chips.com>