drm/rockchip: vop2: fix compile error when CONFIG_DEBUG_FS=n
error logs:
drivers/gpu/drm/rockchip/rockchip_drm_vop2.c:10287:37: error: unused
variable 'vp_data' [-Werror,-Wunused-variable]
        const struct vop2_video_port_data *vp_data = NULL;

Fixes: a0650f480eb8 ("drm/rockchip: vop2: add support get vop aclk rate")
Signed-off-by: Sandy Huang <hjc@rock-chips.com>
Change-Id: I2c711dd62f57232c7dd237a1def9425e4d55e5bf