usb: dwc2: Fix unused variable warning
drivers/usb/dwc2/platform.c: In function '__dwc2_lowlevel_hw_enable':
drivers/usb/dwc2/platform.c:167:33: error: unused variable 'pdev' [-Werror=unused-variable]

Fixes: 95b12ef4ea31 ("usb: dwc2: amend phy operation process")
Change-Id: I6a0300ec54df5cf37d44deed6b210fd2114720fe
Signed-off-by: Tao Huang <huangtao@rock-chips.com>