usb: gadget: configfs: Fix -Wmissing-prototypes warning
drivers/usb/gadget/configfs.c:30:16: error: no previous prototype for 'create_function_device' [-Werror=missing-prototypes]

Fixes: ac360121408c ("ANDROID: usb: gadget: configfs: Add Uevent to notify userspace")
Change-Id: I798b7f650d9ad58e647ab64c0761d428ce64780e
Signed-off-by: Tao Huang <huangtao@rock-chips.com>