dmaengine: rockchip-dma: Fix module compilation when CONFIG_ROCKCHIP_THUNDER_BOOT=y
drivers/dma/rockchip-dma.c:1516:1: error: data definition has no type or storage class [-Werror]
 1516 | arch_initcall_sync(rk_pdma_driver_init);
      | ^~~~~~~~~~~~~~~~~~
drivers/dma/rockchip-dma.c:1516:1: error: type defaults to 'int' in declaration of 'arch_initcall_sync' [-Werror=implicit-int]

Fixes: 081aacf209ea ("dmaengine: rockchip-dma: Call rk_pdma_driver_init() early when CONFIG_ROCKCHIP_THUNDER_BOOT=y")
Change-Id: I5971fdcce7cafeae4b0990a1561edd77c19375bf
Signed-off-by: Tao Huang <huangtao@rock-chips.com>