misc: rockchip: pcie-rkep: Remove unused rkep_mutex
drivers/misc/rockchip/pcie-rkep.c:45:21: error: 'rkep_mutex' defined but not used [-Werror=unused-variable]

Change-Id: I956399d941eeabd9c4787607f8915a6dbdb1f847
Signed-off-by: Tao Huang <huangtao@rock-chips.com>