drm/panel: simple: Add -Wno-unused-const-variable when CONFIG_DRM_PANEL_SIMPLE_OF_ONLY
drivers/gpu/drm/panel/panel-simple.c:5757:36: error: 'osd101t2045_53ts' defined but not used [-Werror=unused-const-variable=]

Change-Id: Ic47d1778e27881a0675fcfd97376b6c7821993e1
Signed-off-by: Tao Huang <huangtao@rock-chips.com>