MALI: mali400: Wrap -Wno-old-style-declaration with cc-option
Clang does not support this option:
error: unknown warning option '-Wno-old-style-declaration';

Fixes: 2981a274bbbc ("MALI: mali400: Changes to adapt kernel 6.12")
Change-Id: I050cf0051cc72ef81d2d88028dde032185d6cb2d
Signed-off-by: Tao Huang <huangtao@rock-chips.com>