dma-buf: rk_heaps: Rename rk_dma_heap_ops callbacks to avoid build error
The callback names in rk_dma_heap_ops conflicted with definitions
in ./include/linux/gfp.h, which caused compilation errors.Rename
rk_dma_heap_ops callbacks as a workaround.

build error message:

drivers/dma-buf/rk_heaps/rk-dma-heap.c: In function ‘rk_dma_heap_alloc_contig_pages’:
./include/linux/alloc_tag.h:217:1: error: expected identifier before ‘(’ token
  217 | ({                                                                      \
      | ^
./include/linux/gfp.h:444:49: note: in expansion of macro ‘alloc_hooks’
  444 | #define alloc_contig_pages(...)                 alloc_hooks(alloc_contig_pages_noprof(__VA_ARGS__))
      |                                                 ^~~~~~~~~~~
drivers/dma-buf/rk_heaps/rk-dma-heap.c:178:27: note: in expansion of macro ‘alloc_contig_pages’
  178 |         return heap->ops->alloc_contig_pages(heap, len, name);
      |                           ^~~~~~~~~~~~~~~~~~
drivers/dma-buf/rk_heaps/rk-dma-heap.c: In function ‘rk_dma_heap_alloc_pages’:
./include/linux/alloc_tag.h:217:1: error: expected identifier before ‘(’ token
  217 | ({                                                                      \
      | ^
./include/linux/gfp.h:333:49: note: in expansion of macro ‘alloc_hooks’
  333 | #define alloc_pages(...)                        alloc_hooks(alloc_pages_noprof(__VA_ARGS__))
      |                                                 ^~~~~~~~~~~
drivers/dma-buf/rk_heaps/rk-dma-heap.c:220:27: note: in expansion of macro ‘alloc_pages’
  220 |         return heap->ops->alloc_pages(heap, pages, len, flags, name);
      |                           ^~~~~~~~~~~
drivers/dma-buf/rk_heaps/rk-dma-heap.c: In function ‘rk_dma_heap_alloc_contig_pages’:
drivers/dma-buf/rk_heaps/rk-dma-heap.c:179:1: error: control reaches end of non-void function [-Werror=return-type]
  179 | }
      | ^
drivers/dma-buf/rk_heaps/rk-dma-heap.c: In function ‘rk_dma_heap_alloc_pages’:
drivers/dma-buf/rk_heaps/rk-dma-heap.c:221:1: error: control reaches end of non-void function [-Werror=return-type]
  221 | }
      | ^
cc1: all warnings being treated as errors

Change-Id: I5677fc1e0ca033b05646305508a0433e8c38d165
Signed-off-by: Simon Xue <xxm@rock-chips.com>